### ISSUE TITLE
0xProject

### ISSUE THREAD

**Issue by expede** [Finhaven/whitepaper-club#2]
- [ ] https://github.com/0xProject/whitepaper
- [ ] https://github.com/0xProject/0x.js/tree/development/packages/contracts

**Comment by naumenkogs** [comment]
1. What if a relayer is malicious? What if a relayer is gonna sell VIP accounts to show orders to special people.
2. Network impact. A lot of double-spending/forks because of no central authority.
3. Bad user/trading experience — high-frequency trading
4. Limited to Ethereum
5. What happens if we have a huge hard fork like ETC? Replayable orders?
6. CI strategy
7. Token registry
8. ROUNDING_ERROR_TOO_LARGE
9. removeAuthorizedAddress method design
